apiVersion: v1
kind: Namespace
metadata:
  name: iplink
---
apiVersion: apps/v1
kind: Deployment 
metadata:
  namespace: iplink
  name: iplink
spec:
  restartPolicy: Always
  replicas: 1
  selector:
    matchLabels:
      app: iplink
  template:
    metadata:
      labels:
        app: iplink
    spec:
      containers:
        - name: iplink
          image: ghcr.io/backchristoffer/iplink:master
          imagePullPolicy: "IfNotPresent"