---
- name: Deploys iperf3 server
  hosts: localhost
  connection: local
  tasks:
  
    - name: Creates iplink namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: namespace
          metadata:
            name: iplink
    
    - name: Deploy iperf3 server
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: apps/v1
          kind: Deployment
          metadata:
            namespace: iplink
            name: iperf3-server-deployment
            labels:
              app: iperf3-server
          spec:
            replicas: 1
            selector:
              matchLabels:
                app: iperf3-server
            template:
              metadata:
                labels:
                  app: iperf3-server
              spec:
                affinity:
                  nodeAffinity:
                    preferredDuringSchedulingIgnoredDuringExecution:
                    - weight: 1
                      preference:
                        matchExpressions:
                        - key: kubernetes.io/role
                          operator: In
                          values:
                          - master
                tolerations:
                  - key: node-role.kubernetes.io/master
                    operator: Exists
                    effect: NoSchedule
                containers:
                - name: iperf3-server
                  image: ghcr.io/backchristoffer/iperf3:latest
                  args: ['-s']
                  ports:
                  - containerPort: 5201
                    name: server
                terminationGracePeriodSeconds: 0

    - name: Deploy iperf3 service
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Service
          metadata:
            namespace: iplink
            name: iperf3-server
          spec:
            selector:
              app: iperf3-server
            ports:
            - protocol: TCP
              port: 5201
              targetPort: server
