name: build and push iplink

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image and push to github
      run: docker build . --file src/iplink_src/Dockerfile --tag iplink:latest
    - name: Tag image
      run: docker image tag iplink:latest ghcr.io/backchristoffer/iplink:latest
    - name: Push image to github
      run: docker image push iplink:latest ghcr.io/backchristoffer/iplink:latest