name: publish Docker
on: [push]
jobs:
 publish-iplink-docker-image:
  runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Login to GitHub Container Registry
uses: docker/login-action@v1
with:
registry: ghcr.io
username: ${{ github.actor }}
password: ${{ secrets.GITHUB_TOKEN }}
- name: Build the hello-docker Docker image
  run: |
    docker build . --tag ghcr.io/backchristoffer/iplink:latest
    docker run ghcr.io/backchristoffer/iplink:latest
    docker push ghcr.io/backchristoffer/iplink:latest
